// <auto-generated />
namespace NominaTarea.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class nominaClass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nominaClass));
        
        string IMigrationMetadata.Id
        {
            get { return "201904030425445_nominaClass"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
